// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7DX3BqQKiIgp3nxDLIoNFbsxlA2ewfnQ',
    appId: '1:656818573936:web:6d52af94cfaa07b0bc5ab5',
    messagingSenderId: '656818573936',
    projectId: 'whatsapp-clone-f8127',
    authDomain: 'whatsapp-clone-f8127.firebaseapp.com',
    storageBucket: 'whatsapp-clone-f8127.firebasestorage.app',
    measurementId: 'G-808RNCFKF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOB-h3SFy-OW3S0-V6uTqKKNKoyU3av-E',
    appId: '1:656818573936:android:f7c41c6ce57b8c50bc5ab5',
    messagingSenderId: '656818573936',
    projectId: 'whatsapp-clone-f8127',
    storageBucket: 'whatsapp-clone-f8127.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2-xqcJuSGxccuB1HxnAMsGdhYiWBXUMo',
    appId: '1:656818573936:ios:81999a715135baedbc5ab5',
    messagingSenderId: '656818573936',
    projectId: 'whatsapp-clone-f8127',
    storageBucket: 'whatsapp-clone-f8127.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2-xqcJuSGxccuB1HxnAMsGdhYiWBXUMo',
    appId: '1:656818573936:ios:81999a715135baedbc5ab5',
    messagingSenderId: '656818573936',
    projectId: 'whatsapp-clone-f8127',
    storageBucket: 'whatsapp-clone-f8127.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7DX3BqQKiIgp3nxDLIoNFbsxlA2ewfnQ',
    appId: '1:656818573936:web:d0a321468f9a7312bc5ab5',
    messagingSenderId: '656818573936',
    projectId: 'whatsapp-clone-f8127',
    authDomain: 'whatsapp-clone-f8127.firebaseapp.com',
    storageBucket: 'whatsapp-clone-f8127.firebasestorage.app',
    measurementId: 'G-7WPSJGEELS',
  );
}
